// examples/solidstart/src/routes/index.tsx
import { Title } from "@solidjs/meta";
import { createAsync, query, type RouteDefinition } from "@solidjs/router";
import { createSignal, Show } from "solid-js";
import { runRustDemo, type RustDemoResult } from "~/lib/rust";

// `runRustDemo` lives in a module-level "use server" file, so this query runs
// the Rust call on the server: directly during SSR, via RPC on client-side
// navigation. Either way the native addon only ever executes in Node.
const getRustDemo = query(() => runRustDemo(), "rust-demo");

export const route = {
  preload: () => getRustDemo(),
} satisfies RouteDefinition;

export default function Home() {
  const rust = createAsync(() => getRustDemo());
  // Client-initiated RPC: calling the "use server" function from browser code
  // POSTs to /_server and runs the Rust in the server-fns bundle — the other
  // server-side pass vinxi builds.
  const [rpc, setRpc] = createSignal<RustDemoResult | null>(null);
  return (
    <main>
      <Title>SolidStart + Rust</Title>
      <h1>SolidStart calling Rust via vite-plugin-native-rust</h1>
      <Show when={rust()} fallback={<p>Computing…</p>}>
        {(r) => (
          <dl>
            <dt>
              <code>add(2, 3)</code> — sync <code>#[napi]</code> fn
            </dt>
            <dd id="add">{r().add}</dd>
            <dt>
              <code>await sumTo(1000)</code> — async <code>#[napi]</code> fn, off
              the event loop
            </dt>
            <dd id="sum-to">{r().sumTo}</dd>
            <dt>Executed on</dt>
            <dd id="runtime">{r().runtime}</dd>
          </dl>
        )}
      </Show>
      <p>
        <button
          id="rpc-button"
          onClick={async () => setRpc(await runRustDemo())}
        >
          Run again from the browser (server-function RPC)
        </button>{" "}
        <Show when={rpc()}>
          {(r) => (
            <span id="rpc-result">
              → add: {r().add}, sumTo: {r().sumTo} ({r().runtime})
            </span>
          )}
        </Show>
      </p>
      <p>
        JSON version at <a href="/api/rust">/api/rust</a>.
      </p>
    </main>
  );
}

// examples/tanstack-start/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import { add, sumTo } from "../server/rust.server";

/**
 * A server function whose handler calls straight into the compiled Rust
 * addon. Start compiles the handler (and the imports only it uses — the
 * `.rs`-backed `rust.server` module above) out of the client bundle; the
 * browser gets an RPC stub that fetches this result over HTTP.
 */
const getRustValues = createServerFn({ method: "GET" }).handler(async () => {
  const start = performance.now();
  const five = add(2, 3); // sync #[napi] fn — runs on the main thread
  const total = await sumTo(1000); // async #[napi] fn — off the event loop
  const ms = performance.now() - start;
  return { add: five, sumTo: total, ms, node: process.version };
});

export const Route = createFileRoute("/")({
  loader: () => getRustValues(),
  component: Home,
});

function Home() {
  const data = Route.useLoaderData();
  return (
    <main style={{ fontFamily: "system-ui", padding: "2rem" }}>
      <h1>TanStack Start + vite-plugin-native-rust</h1>
      <p>
        The route loader calls a <code>createServerFn</code> whose handler
        imports <code>native/src/lib.rs</code> — compiled to a napi-rs native
        addon by the Vite plugin.
      </p>
      <ul>
        <li>
          <code>add(2, 3)</code> = <strong data-testid="add">{data.add}</strong>
        </li>
        <li>
          <code>await sumTo(1000)</code> ={" "}
          <strong data-testid="sumTo">{data.sumTo}</strong>
        </li>
      </ul>
      <p>
        Rust calls took {data.ms.toFixed(3)} ms on Node {data.node}. JSON
        endpoint: <a href="/api/rust">/api/rust</a>
      </p>
    </main>
  );
}
